name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build container
        run: docker build -t wundergraph .

      - name: Delete app
        continue-on-error: true
        run: rm -rf testapp || true